[default.extend-identifiers]
"1beed833" = "1beed833"
"8ba6de7" = "8ba6de7"
"ba952037" = "ba952037"
"metatada" = "metatada"
"tenup_headless_wp_search_title_variables_replacments" = "tenup_headless_wp_search_title_variables_replacments"

[default.extend-words]
"automattic" = "automattic"
"Bui" = "Bui"
"conveniant" = "conveniant"
"convenit" = "convenit"
"littel" = "littel"
"MILION" = "MILION"
"nam" = "nam"
"optio" = "optio"
"varius" = "varius"
