import { defineConfig } from "vite-plus";

/**
 * Repo-wide Vite+ config.
 *
 * This file is the root toolchain config only -- it does no bundling. Each
 * workspace that builds has its own vite.config.* alongside its package.json.
 *
 * Oxlint (`vp lint`) replaces ESLint here. @10up/eslint-config pinned the repo
 * to ESLint 8 (EOL) via eslint-config-airbnb and @wordpress/eslint-plugin, and
 * was the source of the repo's remaining high-severity advisories.
 */
export default defineConfig({
  lint: {
    rules: {
      // Unused catch bindings are idiomatic in this codebase -- plenty of
      // `catch (e) { /* fall through to a default */ }`. Oxlint's
      // no-unused-vars flags every one of them, so turn that dimension of
      // the rule off repo-wide rather than annotating each site.
      "no-unused-vars": ["warn", { caughtErrors: "none" }],

      // Style-only rules from oxlint's unicorn set. These flag working,
      // readable code on aesthetic grounds; churning the codebase for them
      // buys nothing, so they stay off rather than accumulating as warnings
      // everyone learns to scroll past.
      "unicorn/no-useless-spread": "off",
      "unicorn/no-useless-fallback-in-spread": "off",
      "unicorn/no-empty-file": "off",
      "unicorn/prefer-string-starts-ends-with": "off",
    },

    overrides: [
      {
        // Tests assert on fixtures they control, so a throw from an
        // unexpectedly-undefined value IS the failure signal. Keep the
        // rule on for src/, where it catches real TypeErrors.
        files: ["**/__tests__/**", "**/*.test.ts", "**/*.test.tsx"],
        rules: {
          "no-unsafe-optional-chaining": "off",
        },
      },
    ],

    ignorePatterns: [
      // Generated by `next build` -- regenerated on every build, never edited.
      "**/next-env.d.ts",
      "**/dist/**",
      "**/.next/**",
      "**/vendor/**",
      "**/node_modules/**",
      "wp/headless-wp/**",
    ],
  },

  fmt: {
    ignorePatterns: [
      "**/*.css",
      "**/*.html",
      "**/*.json",
      "**/LICENSE.md",
      "**/dist/**",
      "**/.next/**",
      "**/vendor/**",
      "wp/headless-wp/**",
    ],
  },

  // Replaces .lintstagedrc.json; run from .husky/pre-commit via `vp staged`.
  staged: {
    "*.{js,jsx,ts,tsx}": "vp check --fix",
    // phpcs comes from 10up/phpcs-composer in the headless-wp plugin.
    // Without --standard, phpcs silently falls back to its built-in PEAR
    // ruleset and floods the hook with thousands of irrelevant errors.
    "*.php":
      "./wp/headless-wp/vendor/bin/phpcs --standard=./wp/headless-wp/phpcs.xml --extensions=php --warning-severity=8 -s",
  },
});
