import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { PreviewIndicator, queryAppSettings } from '@headstartwp/next/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const { menu } = await queryAppSettings({ menu: 'primary' });

	return (
		<html lang="en">
			<body className={inter.className}>
				{menu ? JSON.stringify(menu) : null}
				{children}
				<PreviewIndicator className="form-container" />
			</body>
		</html>
	);
};

export default RootLayout;
