import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { PreviewIndicator } from '@headstartwp/next/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<PreviewIndicator />
			</body>
		</html>
	);
};

export default RootLayout;
