name: Deploy to Develop ( headless.10uplabs.com )

on: 
  push:
    branches:
      - develop
      - feature/dev-deploy-setup # for testing

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      # useful for emulation and building for different architectures
      - name: Set Up QEMU 
        uses: docker/setup-qemu-action@v2

      # Use Dockers Buildx build plugin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # set image tag to the branch name
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=ref,enable=true,priority=600,prefix=,suffix,event=branch
          images: |
            ${{ secrets.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}

      # TODO: Login to docker hub
      - name: Build container and push to Github Packages
        uses: docker/build-push-action@v4
        with:
          file: deploy/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          context: .

