name: Deploy to Develop ( headless.10uplabs.com )

on: 
  push:
    branches:
      - develop
      - feature/dev-deploy-setup # for testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      # build application
      - name: Build Packages
        run: npm run build:packages
      - name: Build wp-nextjs
        run: npm run build -- --filter=./projects/wp-nextjs

  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      # useful for emulation and building for different architectures
      - name: Set Up QEMU 
        uses: docker/setup-qemu-action@v2

      # Use Dockers Buildx build plugin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Login to docker hub
      - name: Build container and push to ...
        uses: docker/build-push-action@v4
        with:
          file: deploy/Dockerfile
          push: false #TODO: Update to true when we login
          context: .

